#!/bin/bash

#########################

ARCH="armv7"

SDK_VERSION="5.0"
PARALLEL_NUM=1

CURL_VERSION=7.21.5
LIBEVENT_VERSION="2.0.15-stable"
OPENSSL_VERSION=1.0.0e
TRANSMISSION_VERSION=2.41

#########################
