#!/bin/bash

#########################

ARCH="armv7"

DEVFOLDER="/Applications/Xcode.app/Contents/Developer"
# an SDK prior to 6.0 is required if the target ARCH is armv6
SDK_VERSION="6.0"
PARALLEL_NUM=1

CURL_VERSION=7.21.5
LIBEVENT_VERSION="2.0.16-stable"
OPENSSL_VERSION=1.0.0e
TRANSMISSION_VERSION=2.61

#########################

if [ -z ${ARCH} ]; then ARCH="system"; fi
